apiVersion: apps/v1
kind: Deployment
metadata:
  name: itsyourmeals-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: itsyourmeals
  template:
    metadata:
      labels:
        app: itsyourmeals
    spec:
      containers:
      - name: itsyourmeals
        image: pranjalsingh1/simple-test:1.0.0   # Your Docker Hub image
        ports:
        - containerPort: 80
